"""init

Revision ID: 48b989661635
Revises: 
Create Date: 2024-06-02 10:50:42.100863

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = '48b989661635'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim',
    sa.Column('service_dttm', sa.DateTime(), nullable=False),
    sa.Column('submitted_proc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('group_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subscriber_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider_npi', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('provider_fees', sa.Float(), nullable=False),
    sa.Column('allowed_fees', sa.Float(), nullable=False),
    sa.Column('member_co_ins', sa.Float(), nullable=False),
    sa.Column('member_co_pay', sa.Float(), nullable=False),
    sa.Column('quadrant', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claim')
    # ### end Alembic commands ###
